### ISSUE TITLE
Check for pre-requisites in library

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome#128]
There are two pre-requisites, that need to be fullfilled to use this library:
- SysAp Version 2
- SysAp Firmware > 2.6.0

At the moment we don't have enough insight to know how to determine the SysAp version and the firmware is only checked in the HA-integration.

Shouldn't the pre-requisites check move from the HA-integration to the library and the HA-integration only checks a function?

**Comment by kingsleyadam** [comment]
We can definitely add it to the documentation here. We could add a simple method to the `FreeAtHomeSettings` class `has_api_support` which can be used to check capabilities. Home Assistant could call this method and if there is no api support then throw out an error to the user.

But I'd expect whatever application is implementing the `FreeAtHomeApi` class to run the checks themselves. Otherwise we're adding additional requests to check the version within the `FreeAtHomeApi` object which we should avoid. The `FreeAtHomeApi` object shouldn't care which firmware the SysAP is running, it has it's own api version it references (e.g. `v1`).

**Comment by derjoerg** [comment]
If ABB/Busch-Jaeger care about the general rule regarding `v1` I'm absolutely with you. But if they just add additional methods and/or change existing methods without modifying the version we might have a problem.

**Comment by kingsleyadam** [comment]
> If ABB/Busch-Jaeger care about the general rule regarding `v1` I'm absolutely with you. But if they just add additional methods and/or change existing methods without modifying the version we might have a problem.

Yep, that's true. Let's hope they respect the api versioning methods. :) Until then we can assume they will. If they didn't we'd have to make changed to this repo anyway.

I do like adding a `has_api_support` method to `FreeAtHomeSettings` so we can control which firmware is supported. And if a api version is released in the future we can add another method that returns which api version to use.
